---
# tasks file for create_partition
#- parted:
#    device: /dev/sdb
#    number: 1
#    state: present

#- name: Create a ext4 filesystem on /dev/sdb1
#  filesystem:
#    fstype: ext4
#    dev: /dev/sdb1
    
- name: Mount disk /dev/sdb1
  mount: 
    path: /monitor
    src: /dev/sdb1
    fstype: ext4
    state: mounted

- name: To show df -h
  shell: df -h
  register: df

- debug:
    msg: "{{ df.stdout_lines }}"


